<?php
define('MINUTE_IN_SECONDS', 0);
define('HOUR_IN_SECONDS', 0);
define('DAY_IN_SECONDS', 0);
define('WEEK_IN_SECONDS', 0);
define('MONTH_IN_SECONDS', 0);
define('YEAR_IN_SECONDS', 0);

define('WP_CRON_LOCK_TIMEOUT', 0);

define('WP_PLUGIN_DIR', '');
define('WPMU_PLUGIN_DIR', '');
define('WP_DEBUG', false);
define('ABSPATH', '');
define('WP_CONTENT_URL', '');
define('COOKIEPATH', '');
define('COOKIE_DOMAIN', '');
