<?php
defined('ABSPATH') || exit;

// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash,WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- not necessary
if (($_SERVER['REQUEST_METHOD'] ?? '') === 'POST') {
    check_admin_referer('monitor-save');

    if (isset($_POST['save'])) {
        $data = wp_kses_post_deep(wp_unslash($_POST['data']));

        update_option('monitor_settings', $data);
    }

    if (isset($_POST['clean'])) {
        monitor_clean_logs();
    }
}

$data = get_option('monitor_settings', []);

wp_enqueue_script('dashboard');

$log_days = $data['log_days'] ?? 30;
$report = $data['report'] ?? '';
$alerts = $data['alerts'] ?? '';
?>
<div class="wrap">
    <h2>Monitor</h2>

    <p>
        Monitor keeps an eye on WP events (emails, background tasks, ...) providing
        statistics and logs. If you have any specific need, write me at stefano@satollo.net.
    </p>

    <p>
        <a href="https://www.satollo.net/plugins/monitor" target="_blank">Please read the official page</a> until I find the time to integrate more information
        directly on the monitor pages. Thank you.
    </p>


    <form method="post">
        <?php wp_nonce_field('monitor-save'); ?>
        <table class="form-table" role="presentation">
            <tr>
                <th>
                    <?php esc_html_e('Monitor emails', 'monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[emails]" <?= isset($data['emails']) ? 'checked' : ''; ?>>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Monitor the abilities', 'monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[abilities]" <?php echo isset($data['abilities']) ? 'checked' : ''; ?>>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Monitor the scheduler', 'monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[scheduler]" <?php echo isset($data['scheduler']) ? 'checked' : ''; ?>>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Monitor the HTTP calls', 'monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[http]" <?php echo isset($data['http']) ? 'checked' : ''; ?>>
                    <p class="description">
                        HTTP connections made using the native PHP functions (curl, file_get_contents, sockets, ...) are not monitored.
                    </p>
                </td>
            </tr>


            <tr>
                <th>
                    <?php esc_html_e('Include the wp-cron.php autocall', 'monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[http_wpcron]" <?php echo isset($data['http_wpcron']) ? 'checked' : ''; ?>>
                    <p class="description">
                        WP makes HTTP calls to its <code>wp-cron.php</code> script to keep the internal scehduler active,
                        you may want or not to log them.
                    </p>
                </td>
            </tr>

            <tr>
                <th>
                    <?php esc_html_e('Monitor the REST API calls', 'monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[rest]" <?php echo isset($data['rest']) ? 'checked' : ''; ?>>
                    <p class="description">
                    </p>
                </td>
            </tr>

            <tr>
                <th>
                    <?php esc_html_e('Include the wp/v2 calls', 'monitor'); ?>
                    Include the wp/v2 calls
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[rest_wpv2]" <?php echo isset($data['rest_wpv2']) ? 'checked' : ''; ?>>
                    <p class="description">
                        Usually they're a lot and generated by Gutenberg, for example.
                    </p>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Retention', 'monitor'); ?>
                </th>
                <td>
                    <select name="data[log_days]">
                        <option value="15" <?php echo $log_days == 15 ? 'selected' : ''; ?>>15</option>
                        <option value="30" <?php echo $log_days == 30 ? 'selected' : ''; ?>>30</option>
                        <option value="60" <?php echo $log_days == 60 ? 'selected' : ''; ?>>60</option>
                        <option value="90" <?php echo $log_days == 90 ? 'selected' : ''; ?>>90</option>
                    </select>
                    <?php esc_html_e('days', 'monitor'); ?>
                    <button class="button button-secondary" name="clean"><?php esc_html_e('Clean now', 'monitor'); ?></button>
                </td>
            </tr>

        </table>
        <button class="button button-primary" name="save"><?php esc_html_e('Save', 'monitor'); ?></button>
    </form>

    <h3>Debug</h3>
    <pre><?php echo esc_html(print_r($data, true)); ?></pre>

</div>
