<?php
defined('ABSPATH') || exit;

// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash,WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- not necessary
if (($_SERVER['REQUEST_METHOD'] ?? '') === 'POST') {
    check_admin_referer('monitor-save');

    if (isset($_POST['save'])) {
        $data = wp_kses_post_deep(wp_unslash($_POST['data']));

        update_option('monitor_settings', $data);

//        if (isset($data['report'])) {
//            wp_unschedule_hook('monitor_report');
//            $report_time = new DateTime('07:00:00', wp_timezone());
//            wp_schedule_event($report_time->getTimestamp() + DAY_IN_SECONDS, 'daily', '\Satollo\Monitor\monitor_report');
//        } else {
//            wp_unschedule_hook('monitor_report');
//        }
    }



    if (isset($_POST['clean'])) {
        monitor_clean_logs();
    }

    if (isset($_POST['report'])) {
        \Satollo\Monitor\monitor_report();
    }
}

$data = get_option('monitor_settings', []);

wp_enqueue_script('dashboard');

$log_days = $data['log_days'] ?? 30;
?>
<?php include __DIR__ . '/menu.php'; ?>
<div class="wrap">

    <form method="post">
        <?php wp_nonce_field('monitor-save'); ?>
        <table class="form-table" role="presentation">
            <tr>
                <th>
                    <?php esc_html_e('Monitor AI Client', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[aiclient]" <?= isset($data['aiclient']) ? 'checked' : ''; ?>>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Monitor emails', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[emails]" <?= isset($data['emails']) ? 'checked' : ''; ?>>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Monitor the abilities', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[abilities]" <?php echo isset($data['abilities']) ? 'checked' : ''; ?>>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Monitor the scheduler', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[scheduler]" <?php echo isset($data['scheduler']) ? 'checked' : ''; ?>>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Monitor PHP errors', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[php]" <?php echo isset($data['php']) ? 'checked' : ''; ?>>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Monitor the HTTP calls', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[http]" <?php echo isset($data['http']) ? 'checked' : ''; ?>>
                    <p class="description">
                        HTTP connections made using the native PHP functions (curl, file_get_contents, sockets, ...) are not monitored.
                    </p>
                </td>
            </tr>


            <tr>
                <th>
                    <?php esc_html_e('Include the wp-cron.php autocall', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[http_wpcron]" <?php echo isset($data['http_wpcron']) ? 'checked' : ''; ?>>
                    <p class="description">
                        WP makes HTTP calls to its <code>wp-cron.php</code> script to keep the internal scehduler active,
                        you may want or not to log them.
                    </p>
                </td>
            </tr>

            <tr>
                <th>
                    <?php esc_html_e('Monitor the REST API calls', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[rest]" <?php echo isset($data['rest']) ? 'checked' : ''; ?>>
                    <p class="description">
                    </p>
                </td>
            </tr>

            <tr>
                <th>
                    <?php esc_html_e('Include the wp/v2 calls', 'satollo-monitor'); ?>
                    Include the wp/v2 calls
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[rest_wpv2]" <?php echo isset($data['rest_wpv2']) ? 'checked' : ''; ?>>
                    <p class="description">
                        Usually they're a lot and generated by Gutenberg, for example.
                    </p>
                </td>
            </tr>
            <tr>
                <th>
                    <?php esc_html_e('Retention', 'satollo-monitor'); ?>
                </th>
                <td>
                    <select name="data[log_days]">
                        <option value="15" <?php echo $log_days == 15 ? 'selected' : ''; ?>>15</option>
                        <option value="30" <?php echo $log_days == 30 ? 'selected' : ''; ?>>30</option>
                        <option value="60" <?php echo $log_days == 60 ? 'selected' : ''; ?>>60</option>
                        <option value="90" <?php echo $log_days == 90 ? 'selected' : ''; ?>>90</option>
                    </select>
                    <?php esc_html_e('days', 'satollo-monitor'); ?>
                    <button class="button button-secondary" name="clean"><?php esc_html_e('Clean now', 'satollo-monitor'); ?></button>
                </td>
            </tr>

            <tr>
                <th>
                    <?php esc_html_e('MCP', 'satollo-monitor'); ?>
                </th>
                <td>
                    <input type="checkbox" value="1" name="data[mcp]" <?php echo isset($data['mcp']) ? 'checked' : ''; ?>>
                    <p class="description">
                        Set the abilities to be exposed by the defailt MCP server (if present).
                    </p>
                </td>
            </tr>

            <?php if (WP_DEBUG) { ?>
                <tr>
                    <th>
                        <?php esc_html_e('Report', 'satollo-monitor'); ?>
                    </th>
                    <td>
                        <input type="checkbox" value="1" name="data[report]" <?php echo isset($data['report']) ? 'checked' : ''; ?>>


                        <p class="description">
                            Send daily report to <?= esc_html(get_option('admin_email')) ?>.
                            <?php
                            if (isset($data['report'])) {
                                echo 'Next: ', esc_html(wp_date(get_option('date_format') . ' ' . get_option('time_format'), wp_next_scheduled('monitor_report')));
                            }
                            ?>
                        </p>
                        <button class="button button-secondary" name="report"><?php esc_html_e('Send now', 'satollo-monitor'); ?></button>
                    </td>
                </tr>

            <?php } ?>

        </table>
        <button class="button button-primary" name="save"><?php esc_html_e('Save', 'satollo-monitor'); ?></button>


    </form>

    <h3>Debug</h3>
    <pre><?php echo esc_html(print_r($data, true)); ?></pre>

</div>
